### ISSUE TITLE
AppImage crashes on opening any example on Ubuntu 18.04 64bit

### ISSUE THREAD

**Issue by igoryonya** [huxingyi/dust3d#47] opened 2019-11-14 00:02 UTC
![изображение](https://user-images.githubusercontent.com/10928926/68814348-10549200-06d5-11ea-9dac-216cd9ea7d4b.png)
As soon, as I open any example, it appears on the screen, then immediately closes the window (crashes).
The terminal, from which the app is executed, writes:

_
user@host:~/AppImage$ ./dust3d-1.0.0-beta.27-x86_64.AppImage
Исключение в операции с плавающей точкой (стек памяти сброшен на диск)
_
An exception in floating point operation (RAM stack was dumped to disk)

I've tried versions:
dust3d-1.0.0-beta.27-x86_64.AppImage
dust3d-1.0.0-beta.26-x86_64.AppImage

**Comment by huxingyi** [comment] 2019-11-14 09:50
Thanks for reporting, I tested dust3d-1.0.0-beta.27-x86_64.AppImage on virtualbox which installed ubuntu-18.04.3-desktop-amd64.iso, but couldn't reproduce it.
Did you see the rendered model before it crashes?

**Comment by igoryonya** [comment] 2019-11-15 04:04
It crashes as soon, as being rendered, immediately

**Comment by igoryonya** [comment] 2019-11-15 04:29
I closed it by accident, I thought, it closes the text box.

**Comment by huxingyi** [comment] 2019-11-15 08:06
Hi, @igoryonya No worries, let's reopen this issue.

Since I don't have a AMD cpu machine to test, could you help me to debug it and get the stack trace of the crash please?

`$ gdb ./dust3d-1.0.0-beta.27-x86_64.AppImage`
`(gdb) r`

When it crashes, you should see something like this:
Thread 1 "dust3d" received signal SIGABRT, Aborted.
..... ...
`(gdb) bt`

There should be stack trace info listed below, please copy the stack trace info, save to a text file and drag that text file to the comment box, or save it as a picture and drag it here.
(Don't copy the stack trace text directly to here, it has the sharp character '#' which will cause github link it as issue id)

Thanks!

**Comment by huxingyi** [comment] 2023-08-13 00:22
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.

**Closed by huxingyi** 2023-08-13 00:22 UTC
