### ISSUE TITLE
Opening an image url in the change reference sheet window causes program to freeze

### ISSUE THREAD

**Issue by justStand** [huxingyi/dust3d#25] opened 2018-12-02 22:18 UTC

**Comment by huxingyi** [comment] 2018-12-03 12:07
Hi, thanks for reporting, mind me ask more info to further trace the bug please?  
1. Which version of Dust3D and,  
2. What OS(Windows/Linux/MacOS) are you using  
3. Is the [example ds3](https://blogs.dust3d.org/public/attachments/2018-11-29-the-game-asset-pipeline/guitar.ds3) file could been open normally?  
4. Is only jpeg could cause freeze or png also?

**Comment by justStand** [comment] 2018-12-08 01:16
It only happens if you try to open a website address, not an image on the hard drive.

**Comment by justStand** [comment] 2018-12-08 01:17
Accidentally closed it.

**Comment by huxingyi** [comment] 2018-12-08 01:48
Thanks for clarifying, I can reproduce it in windows 7. Surprisingly windows support opening a url in the file dialog. Will look into it further.

**Comment by huxingyi** [comment] 2018-12-08 03:40
Hi, I have verified it's a QT bug: https://bugreports.qt.io/browse/QTBUG-63645 and looks like it was been fixed in Qt5.9.4 but we are using Qt5.10.1 on windows for Dust3D, so the bug is still there.
Since it's a QT bug, there isn't an easy fix could be done in Dust3D, so I am closing this issue now. We may use another advanced version number of Qt in the future.
Thanks!

**Closed by huxingyi** 2018-12-08 03:40 UTC
